server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: User
          uri: http://localhost:8082
          predicates:
            - Path=/users/** 
        - id: Menu
          uri: http://localhost:8083
          predicates:
            - Path=/menus/** 
        - id: status
          uri: http://localhost:8084
          predicates:
            - Path= /statusTables/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: User
          uri: http://User:8080
          predicates:
            - Path=/users/** 
        - id: Menu
          uri: http://Menu:8080
          predicates:
            - Path=/menus/** 
        - id: status
          uri: http://status:8080
          predicates:
            - Path= /statusTables/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080